import './global.css';

export const metadata = {
  title: 'Welcome to cart',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <p>I'm Root Layout</p>
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
